make: Code/Sources/Error.cpp Code/Sources/Instruction.cpp Code/Sources/InstructionFunctions.cpp Code/Sources/main.cpp Code/Sources/MISProgram.cpp Code/Sources/Parameter.cpp Code/Sources/Util.cpp Code/Sources/Variable.cpp Code/Sources/MicroInstructions.cpp
	g++ -o misvm -std=c++11 Code/Sources/Error.cpp Code/Sources/Instruction.cpp Code/Sources/InstructionFunctions.cpp Code/Sources/main.cpp Code/Sources/MISProgram.cpp Code/Sources/Parameter.cpp Code/Sources/Util.cpp Code/Sources/Variable.cpp Code/Sources/MicroInstructions.cpp

clean: misvm
	rm misvm; rm *.err; rm *.out
